vexctl.o: vexctl.c ../../Libs/C/roboctl.h ../../Libs/C/rct_machdep.h \
  ../../Libs/C/rct_rcx.h ../../Libs/C/rct_nxt.h \
  ../../Libs/C/rct_nxt_output.h ../../Libs/C/rct_pic.h \
  ../../Libs/C/rct_protos.h vexctl_cmd.h protos.h
	${CC} -c ${CFLAGS} vexctl.c

